languages:
  JavaScript: true
  PHP: true

exclude_paths:
  - "application/index.php"
  - "application/.content/cache"
  - "lib/modules/cli/application.class.php"
  - "lib/modules/database.class.php"
  - "lib/tests/CacheTest.php"
  - "lib/tests/DatabaseTest.php"
  - "lib/tests/LocaleTest.php"
  - "lib/tests/LoggingTest.php"
  - "lib/tests/RainTPL4/InterfaceTest.php"
  - "vendor/*"
  - "tests/*"