languages:
  JavaScript: true
  PHP: true

exclude_paths:
  - "application/index.php"
  - "application/.content/cache"
  - "lib/modules/cli/application.class.php"
  - "lib/modules/database.class.php"
  - "lib/tests"