language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

addons:
  code_climate:
    repo_token: a31320388fb4f4b9b96fd2a271bce301c6365c4104dd3ee05db0334309fd3469

before_install:
  - cd lib && composer install --dev
  - cd ..
  - mkdir ./application/.content/cache/translations/ -p
  - chmod 777 ./application/.content/ -R
  - cd application
  - php ../lib/bin/deploy build/environment/developer --coverage --travisci
  - php ../lib/bin/deploy tests/buildTestDatabase

script: phpunit -c ./.content/cache/phpunit.xml.dist

after_script:
  - cd ../lib && php vendor/bin/test-reporter

notifications:
  email: false