language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - 5.5

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: 5.5

addons:
  code_climate:
    repo_token: a31320388fb4f4b9b96fd2a271bce301c6365c4104dd3ee05db0334309fd3469

before_install:
  - git clone https://github.com/Panthera-Framework/example-panthera-application
  - rm -rf lib
  - cd example-panthera-application
  - composer install --dev
  - mkdir .content/cache/translations/ -p
  - chmod 777 ./.content/ -R
  - vendor/pantheraframework/panthera/lib/Binaries/deploy Build/Environment/Developer --coverage --travisci --yes
  - vendor/pantheraframework/panthera/lib/Binaries/deploy Tests/BuildTestDatabase

script: phpunit -c ./.content/cache/phpunit.xml.dist

after_script:
  - php vendor/bin/test-reporter

notifications:
  email: false