language: php

/home/travis/.phpenv/versions/5.4/bin/composer self-update
/home/travis/.phpenv/versions/5.4/bin/composer /home/travis/build/Panthera-Framework/panthera/lib/composer.json install

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php:
      - 7.0
      - nightly
      - hhvm


install: composer install