language: php

php:
  - 5.5
  - 5.6
  - nightly
  - hhvm

addons:
  code_climate:
    repo_token: a31320388fb4f4b9b96fd2a271bce301c6365c4104dd3ee05db0334309fd3469

before_install:
  - cd lib && composer install --dev
  - cd ..

script: cd application && php ../lib/bin/deploy.php tests/PHPUnitConfigure --coverage --travisci && phpunit -c ./.content/cache/phpunit.xml.dist

after_script:
  - cd ../lib && php vendor/bin/test-reporter