build: false
shallow_clone: false
platform: 'x86'
clone_folder: C:\pantheraframework2
branches:
  except:
    - gh-pages

install:
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd C:\pantheraframework2\lib
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction

test_script:
  - cd C:\pantheraframework2\application
  - ../lib/bin/deploy build/environment/developer
  - ../lib/bin/deploy tests