
<!DOCTYPE html>
<html>
<head>
    <title>Error (404)</title>
    <meta charset="utf-8">
    <META NAME="ROBOTS" CONTENT="NOINDEX">
    {include "Errors/ErrorStyles.tpl"}
</head>


<body>
<div id="summary">
    <h1>Not found (404)</h1>

    <ol id="summaryDetails">
        <li><b>Request:</b> {$request.type} {$request.url}</li>
        <li><b>HTTP Referer:</b> {if $request.referer}{$request.referer}{else}NONE{/if}</li>
        <li><b>Server:</b> {$request.server}</li>
        <li><b>Panthera:</b> {$pfVersion}</li>
        <li><b>Application directory:</b> {$appPath}</li>
    </ol>
</div>

<div class="lighter">
    <h1>Avaliable routes</h1>
    <div class="inner">
        <ol>
            {foreach from="$routes" as $route => $data}
                <li>{$data.0} <b>{$route}</b>   ~>  <i>{$data.2}</i></li>
            {/foreach}
        </ol>

        <br/>
        Use `deploy Build/Routing/Cache` to rebuild list of available routes.
    </div>
</div>

<div>
    <h1>Log</h1>
    <div class="inner">
        <pre>{$log}{if !$log}Please enable configuration key "logging/enabled" to see log.
From code or PHP shell you could use: `Framework::getInstance()->config->set('logging/enabled', true); Framework::getInstance()->config->save();`{/if}
        </pre>
    </div>
</div>

<div class="footer">Message generated by Panthera Framework {$pfVersion}</div>
</body>
</html>