#!/usr/bin/env php
<?php
set_time_limit(0); // never stop executing the script

//define('DEBUG', True);

if(!is_file('content/app.php'))
    die("Please run this tool from the root directory of your website\n");

include('content/app.php');

error_reporting(E_ALL);

class ptop extends cliApp
{
    protected $sleepTime = 3;
    protected $_waitAfterHelp = True;

    public function __construct()
    {
        parent::__construct();
        $this->registerCommand('f', 'freeze', 'Freeze input');
        $this->clear(True);

        $this->panthera->importModule('crontab');
        
        $this->panthera->switchPlugin('ptopUpdater', True);
        $this->panthera->config->save(); // save changes to database
    }

    public function freeze($args='')
    {
        print("Output freezed, press [Enter] to continue...");
        $this->wait(9999);
    }

    protected function catchUserInput($input)
    {
        // call parent method
        parent::catchUserInput($input);
    }
    
    public function signalHandler($signal)
    {
        print("Cleaning up...\n");
        $this->panthera->switchPlugin('ptopUpdater', False);
        $this->panthera->config->save();
        sleep(0.5);
        parent::signalHandler($signal);
    }

    protected function main()
    {
        $this->clear();

        print($this->screen->picker->getColoredString("ptop ".PANTHERA_VERSION."\n\n", 'light_cyan'));

        // get all sockets
        $sockets = run::getSockets();

        // list to display in table
        $list = array();

        foreach ($sockets as $socket)
        {
            if ($socket->expired == 0)
                $executionTime = 'still executing';
            else
                $executionTime = round(($socket->expired-$socket->started)*100);

            // unpack data            
            $data = $socket->storage;
            $time = '?';
            
            if (isset($data['time']))
                $time = "page: " .substr($data['time']['page'], 0, 5). ", tpl: " .substr($data['time']['template'], 0, 5). ", overall: " .substr($data['time']['overall'], 0, 5);
                
            if (!isset($data['method']))
                $data['method'] = 'GET';

            $list[] = array('pid' => $socket->pid, 'user' => $data['user'], 'name' => $socket->name, 'execution time' => $executionTime. ' ms', 'triggered by' => $data['client'], 'request method' => $data['method'], 'url' => $data['url'], 'time' => $time);
        }

        if (count($list) == 0)
            $list[] = array('pid' => 'no', 'name' => 'active', 'execution time' => 'processes', 'triggered by' => 'working', 'request method' => 'in background', 'url' => '', 'time' => '');

        $renderer = new ArrayToTextTable($list);
        $renderer->showHeaders(true);
        //$renderer->setMaxWidth(64);
        $renderer->render();

        $processes = 0;

        if ($list[0]['pid'] != 'no')
            $processes = count($list);

        print("\nTotal processes: ".$processes."\nPress [f] to freeze output.");

        print("\n");
        
        // cleanup
        cronjobs::cleanRunSockets();
    }
}

$app = new ptop();
$app -> run();

