<!DOCTYPE html>
<html>
    <head>
	    <meta charset="utf-8">
	    <title>Error - developer informations</title>

        <?php include(getContentDir('templates/error.css.php'));?>

    </head>
    <body>
        <br><br>
        <div class="content">
            <h2 class="err_header">Panthera</h2>
            <p>Application database error occured.</p>
            <br>

            <div class="warning">
                <?php echo $warningMessage; ?>
            </div>

            <div class="error">
                <?php echo $message; ?>
            </div>

            <p style="float: right;"><small>Message generated by Panthera Framework <?php echo PANTHERA_VERSION;?></small></p>
            <br>
        </div>
    </body>
</html>
