<?php
if (!defined('IN_PANTHERA'))
    exit;
?>
<!DOCTYPE html>
<html>
    <head>
        <title>Error - developer informations</title>
        <meta charset="utf-8">
        <META NAME="ROBOTS" CONTENT="NOINDEX">
        <script type="text/javascript" src="{$PANTHERA_URL}/js/panthera.js"></script>
        <?php include getContentDir('templates/error.css.php'); ?>
    </head>
    <?php
                function printUlArray($array)
                {
                    if (count($array))
                    {
                        foreach ($array as $key => $value)
                        {
                            if (!is_array($value))
                                echo '<ul><b>' .$key. '</b> => ' .$value. '</ul>';
                            else {
                                echo ' {<br>';
                                printUlArray($value);
                                echo '<br> }';
                            }
                        }
                    }
                }
            ?>

    <body>
        <div id="summary">
            <h1>Unexpected errors occured in PHP code execution, please take a look at those informations.</h1>
            
            <ol id="summaryDetails">
                <li><b>Message:</b> <span style="color: #C00;"><?php echo $errstr; ?></span></li>
            </ol>
        </div>
        <div class="lighter">
            <h1>Stack trace</h1>
            
            <div class="inner">
            <p>
                <ol>
                    <?php
                        $stack = array_reverse($stack);
                    
                        foreach ($stack as $key => $trace)
                        {
                            $function = '<span class="func_name">' .$trace['function']. '</span>';
    
                            if (isset($trace['class']))
                                $function = '<span class="class_name">' .$trace['class']. '</span> -> <span class="func_name">' .$trace['function']. ' ( ' .implode(', ', $trace['args']). ' )</span>';
    
                            echo '<b>' .$key. '</b> => ' .$function. ' ( ' .implode(', ', $trace['args']). ' )<br>';
                        }
                    ?>
                </ol>
            </p>
            </div>
        </div>
        
        <div>
            <h1>Log</h1>
            <div class="inner"><?php echo str_replace("\n", "\n<br>", htmlspecialchars($panthera->logging->getOutput())); ?></div>
        </div>
        
        <div class="lighter">
            <h1>Informations</h1>
            <div class="inner"><br>
                <h2>GET:</h2>
                <?php printUlArray($_GET); ?><br>
                <h2>POST:</h2>
                <?php printUlArray($_POST); ?><br>
                <h2>SERVER:</h2><br>
                <?php printUlArray($_SERVER); ?><br>
            </div>
        </div>
        
        <div class="footer">Message generated by Panthera Framework <?php echo PANTHERA_VERSION;?></div>
    </body>
</html>


