<?php

if (!defined('IN_PANTHERA'))
    exit;

?>

<!DOCTYPE html>
<html>
    <head>
	    <meta charset="utf-8">
	    <title>Error - developer informations</title>
        <?php include(getContentDir('templates/error.css.php'));?>
    </head>
    <body>
        <br><br>
        <div class="content">
            <h2 class="err_header">Panthera</h2>
            <p>Unexpected errors occured in PHP code execution, please take a look at those informations.</p>
            <br>

            <?php
                if ($errno == E_USER_ERROR)
                    $class = "error"; 
                else
                    $class = "warning";
            ?>

            <div class="<?php echo $class;?>">
                Message:<br>
                <?php echo $details['message']; ?>
            </div>

            <div class="warning">
                Stack trace:<br>
                <?php
                    foreach ($stack as $key => $trace)
                    {
                        $function = '<span class="func_name">' .$trace['function']. '</span>';

                        if (isset($trace['class']))
                            $function = '<span class="class_name">' .$trace['class']. '</span> -> <span class="func_name">' .$trace['function']. ' ( ' .implode(', ', $trace['args']). ' )</span>';

                        echo $key. ' => ' .$function. ' ( ' .implode(', ', $trace['args']). ' )<br>';
                    }
                ?>
            </div>

            <?php
                function printUlArray($array)
                {
                    if (count($array))
                    {
                        foreach ($array as $key => $value)
                        {
                            if (!is_array($value))
                                echo '<ul>' .$key. ' => ' .$value. '</ul>';
                            else
                                printUlArray($value);
                        }
                    }
                }
            ?>

            <div class="success">
                Debugger:<br>
                <?php echo str_replace("\n", "\n<br>", $panthera->logging->getOutput()); ?>
            </div>

            <div class="info">
                Informations:<br><br>
                &nbsp;GET:
                <?php printUlArray($_GET); ?><br>
                <br>&nbsp;POST:
                <?php printUlArray($_POST); ?><br>
                <br>&nbsp;SERVER:
                <?php printUlArray($_SERVER); ?>
                <br><br>Registered hooks:<br><?php printUlArray($panthera->getAllHooks()); ?>
            </div>

            <p style="float: right;"><small>Message generated by Panthera Framework <?php echo PANTHERA_VERSION;?></small></p>
            <br>
        </div>
    </body>
</html>
