<?php

if (!defined('IN_PANTHERA'))
    exit;

?>
<!DOCTYPE html>
<html>
    <head>
        <title>Error - developer informations</title>
        <meta charset="utf-8">
        <META NAME="ROBOTS" CONTENT="NOINDEX">
        <script type="text/javascript" src="{$PANTHERA_URL}/js/panthera.js"></script>
        <?php include getContentDir('templates/error.css.php'); ?>
    </head>
    
    <body>
        <div id="summary">
            <h1>Unhandled exception occured during code execution, please take a look at stack trace.</h1>
            
            <ol id="summaryDetails">
                <li><b>Message:</b> <span style="color: #C00;"><?php echo $exception->getMessage(); ?></span></li>
                <li><b>Place:</b> <span style="color: #C00;"><?php echo $exception->getFile(); ?> on line <?php echo $exception->getLine(); ?></span></li>
            </ol>
        </div>
        <div class="lighter">
            <h1>Stack trace</h1>
            
            <div class="inner">
            <p>
                <ol>
                    <?php
                        foreach (array_reverse($stackTrace) as $trace)
                        {
                            $function = '<span class="func_name">' .$trace['function']. '</span>';
        
                            if (isset($trace['class']))
                                $function = '<span class="class_name">' .$trace['class']. '</span> -> <span class="func_name">' .$trace['function']. '</span>';
        
                            echo '<b>' .$trace['key']. ' =></b> Called ' .$function. ' (' .htmlspecialchars(substr($trace['args_json'], 0, 256)). ' ) in ' .$trace['file']. ' on line <span class="func_name">' .$trace['line']. '</span><br>';
                        }
                    ?>
                </ol>
            </p>
            </div>
        </div>
        
        <div>
            <h1>Plain stack trace</h1>
            <div class="inner">
                <?php echo $exception->getTraceAsString(); ?>
            </div>
        </div>
        
        <div class="lighter">
            <h1>Log</h1>
            <div class="inner"><?php echo str_replace("\n", "\n<br>", htmlspecialchars($panthera->logging->getOutput())); ?></div>
        </div>
        
        <div class="footer">Message generated by Panthera Framework <?php echo PANTHERA_VERSION;?></div>
    </body>
</html>

