<!DOCTYPE html>
<html>
    <head>
	    <meta charset="utf-8">
	    <title>Error - developer informations</title>

        <?php include(getContentDir('templates/error.css.php'));?>

    </head>
    <body>
        <br><br>
        <div class="content">
            <h2 class="err_header">Panthera</h2>
            <p>Unhandled exception occured during code execution, please take a look at stack trace.</p>
            <br>

            <div class="warning">
                <?php echo $exception->getMessage(); ?>
                <br><br>
                <?php echo $exception->getFile(); ?> on line <?php echo $exception->getLine(); ?>
            </div>

            <div class="success">
                Debugger:<br>
                <?php echo str_replace("\n", "\n<br>", htmlspecialchars($panthera->logging->getOutput())); ?>
            </div>

            <div class="error">
            <?php
                foreach ($stackTrace as $trace)
                {
                    $function = '<span class="func_name">' .$trace['function']. '</span>';

                    if (isset($trace['class']))
                        $function = '<span class="class_name">' .$trace['class']. '</span> -> <span class="func_name">' .$trace['function']. '</span>';

                    echo $trace['key']. ' =><br><ul>Called ' .$function. ' (' .htmlspecialchars(substr($trace['args_json'], 0, 256)). ' ) in<br>' .$trace['file']. ' on line <span class="func_name">' .$trace['line']. '</span></ul><br>';
                }
            ?>
            <br>
                <?php echo $exception->getTraceAsString(); ?>
            </div>

            <p style="float: right;"><small>Message generated by Panthera Framework <?php echo PANTHERA_VERSION;?></small></p>
            <br>
        </div>
    </body>
</html>
