<?php
if (!defined('IN_PANTHERA'))
    exit;
?>
<!DOCTYPE html>
<html>
    <head>
        <title>Error (404)</title>
        <meta charset="utf-8">
        <META NAME="ROBOTS" CONTENT="NOINDEX">
        <script type="text/javascript" src="{$PANTHERA_URL}/js/panthera.js"></script>
        <?php include getContentDir('templates/error.css.php'); ?>
    </head>

    <body>
        <div id="summary">
            <h1>Not found (404)</h1>
            
            <ol id="summaryDetails">
                <li><b>Request:</b> <?php print($_SERVER['REQUEST_METHOD']. ' ' .$_SERVER['REQUEST_URI']); ?></li>
                <li><b>HTTP Referer:</b> <?php if(isset($_SERVER['HTTP_REFERER'])) { print($_SERVER['HTTP_REFERER']); } else { print('None');}?></li>
                <li><b>Server:</b> <?php print($_SERVER['SERVER_SOFTWARE']);?></li>
                <li><b>Panthera:</b> <?php print(PANTHERA_VERSION); ?> from <?php print(PANTHERA_DIR);?></li>
                <li><b>Application directory:</b> <?php print(SITE_DIR); ?></li>
            </ol>
        </div>
        
        <div class="lighter">
            <h1>Avaliable routes</h1>
            <div class="inner">
                <ol>
                    <?php
                    foreach ($panthera -> routing -> getRoutes() as $route)
                    {
                        print('<li>' .$route[0]. ' /' .$route[1]. '</li>');  
                    }
                    ?>
                </ol>
            </div>
        </div>
        
        <div>
            <h1>Log</h1>
            <div class="inner">
                <?php echo str_replace("\n", "\n<br>", htmlspecialchars($panthera->logging->getOutput())); ?>
            </div>
        </div>
        
        <div class="footer">Message generated by Panthera Framework <?php echo PANTHERA_VERSION;?></div>
    </body>
</html>